name: CD

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [published]

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: |
          pip install --upgrade setuptools
          pip install numpy cython
          python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  twine_check:
    name: Check if dists can be published
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name != 'release'

    steps:
      - name: Download wheels and sdist
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Check with twine
        run: |
          pip install twine
          twine check dist/* --strict

  publish:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Download wheels and sdist
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p ${{ secrets.pypi_token }}
