name: CI

on: [push, pull_request]

jobs:

  unit-test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.12"]

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: install package
        run: |
          pip install .[test]

      - run: pytest
